Repository attr-encrypted/attr_encrypted, pull requests merged in 2022-10, with the labels that each got.

#383 Add support for Ruby 2.7 and its kwargs
  lib/attr_encrypted/adapters/active_record.rb
Labels: enhancement

#419 Fixed bug where we were comparing versions as strings
  lib/attr_encrypted/adapters/active_record.rb
  test/active_record_test.rb
Labels: bug

#421 Fix typo in README
  README.md
Labels: docs

#422 Fix typo in README
  README.md
Labels: docs
